# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

def shared_pods
    pod 'Alamofire', '~> 4.0'
    pod 'SwiftyJSON', :git => 'https://github.com/acegreen/SwiftyJSON.git', :branch => 'swift3'
    pod 'SVProgressHUD'
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
    pod 'DZNEmptyDataSet', '~> 1.8.1'
    pod 'TextFieldEffects', :git => 'https://github.com/raulriera/TextFieldEffects.git', :tag => '1.3.0'
    pod 'HanekeSwift’, :git => 'https://github.com/Haneke/HanekeSwift.git', :branch => 'feature/swift-3'
    pod 'SwiftDate', '~> 4.0.3'
end

target 'ProofKogi' do

  shared_pods

  # Pods for ProofKogi

  target 'ProofKogiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProofKogiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end